### ISSUE TITLE
关于镜像源问题

### ISSUE THREAD

**Issue by xiepingfu** [YangMame/Arch-Installer#1]
中科大的镜像源某些地方访问不了（比如我.....），建议更换成其它源.

**Comment by YangMame** [comment]
这个考虑到了 在脚本里面写了(163网易云)已被注释掉了 去掉注释就行了

**Comment by YangMame** [comment]
网易的[镜像站](http://mirrors.163.com)应该没问题吧 如果没问题我就全换成网易云的

**Comment by xiepingfu** [comment]
恩，我用网易的镜像站没有问题。还有就是config.sh中我昨天试的时候也是改成官方的仓库才成功的。

**Comment by YangMame** [comment]
了解了 那我换成网易的 主要是因为网易更新比较慢所以才用的中科大
