### ISSUE TITLE
选取镜像源时的错误

### ISSUE THREAD

**Issue by Kurobac** [YangMame/Arch-Installer#12]
现在的livecd(2018.06.01)中，rankmirrors已经属于pacman-contrib这个包了，而livecd没有附带这个包。到选取镜像源的那步会卡住。

**Comment by YangMame** [comment]
Ok，我会尝试修好的，多谢提醒

**Comment by YangMame** [comment]
@Kurobac 已修复

**Comment by Kurobac** [comment]
thanks.
