### ISSUE TITLE
获取脚本失败

### ISSUE THREAD

**Issue by Bryan2333** [YangMame/Arch-Installer#13]
系统一直显示connecting
![default](https://user-images.githubusercontent.com/31512600/42405852-b8d7fd0e-81cf-11e8-981a-1336a941625a.PNG)

**Comment by YangMame** [comment]
挂着这个网站的VPS跑路了。。。。 先用这个链接下载吧：https://github.com/YangMame/Arch-Linux-Installer/raw/master/arch-linux-installer.sh 你可以用 git.io 转为短链接
（不好意思没发现

**Comment by Bryan2333** [comment]
ok,谢谢
