### ISSUE TITLE
小白鼠测试出现的问题

### ISSUE THREAD

**Issue by luzibuye** [YangMame/Arch-Installer#4]
1."Install yaourt from archlinuxcn ? (just for China users) y)YES ENTER)NO"，在这步是选择y以后再选择源，出现了can't find archlinuxcn-keyring。然后就中断了。不知道是不是我的原因。
2.安装桌面时，好像不管选哪个数字都是报错 "Error ! Please input the correct num" = =。
小小的建议：安装过程出错后就中断了，感觉可以设置容错，从错误步骤重新来过。
以上=。=

**Comment by YangMame** [comment]
噢 这个还没测试（只测试了直接下载通过makepkg安装） 忘了加上更新软件源的命令
确实可以设置容错 但是这参数可能不太好用
我会加上的

**Comment by YangMame** [comment]
噢 这个还没测试（只测试了直接下载通过makepkg安装） 忘了加上更新软件源的命令
确实可以设置容错 但是这参数可能不太好用
我会加上的

**Comment by luzibuye** [comment]
选择桌面环境那里不管哪个数字，都是报错的。。

**Comment by YangMame** [comment]
@jasooner 已修复

**Comment by YangMame** [comment]
@jasooner 多谢测试 哈哈哈哈 现在应该没什么大毛病了
