### ISSUE TITLE
grub安装失败

### ISSUE THREAD

**Issue by GreenHatHG** [YangMame/Arch-Installer#8]
![image](https://user-images.githubusercontent.com/34258355/35738580-37c1c008-086a-11e8-8060-c98fdf7695d7.png)虚拟机环境，不知道为什么

**Comment by YangMame** [comment]
@GreenHatHG 分区类型请换成mbr gpt是uefi用的

**Comment by GreenHatHG** [comment]
我的笔记本已经开启了bios启动模式(开启gsm)，关闭了uefi，机械硬盘也是mbr的，不知道是怎么回事，谢谢

**Comment by YangMame** [comment]
@GreenHatHG 给俺看看`fdisk -l`的输出，这个与实体机的情况不相关。如果是虚拟机，legacy+mbr比较好，最好是能清除当前的分区类型新建为mbr再安装，实体机的话确保为legacy+mbr或uefi+gpt启动（不建议开csm，因为你可能会搞混俩者）

**Comment by GreenHatHG** [comment]
开启了gsm不就是关闭了uefi？

**Comment by YangMame** [comment]
@GreenHatHG 并不是 还有 你说的是csm吧 csm只是个兼任模块让uefi也可以启动legacy

**Comment by GreenHatHG** [comment]
除了csm，好像我在bios没要找到其他开关uefi选项了

**Comment by YangMame** [comment]
@GreenHatHG 要么只用uefi 要么只用legacy 俩者混在一起并不好用

**Comment by GreenHatHG** [comment]
好的，谢谢
