### ISSUE TITLE
添加用户失败

### ISSUE THREAD

**Issue by Bryan2333** [YangMame/Arch-Installer#9]
![img_20180211_172752](https://user-images.githubusercontent.com/31512600/36092264-b5167e7c-1021-11e8-9a06-aab055f13147.jpg)

**Comment by YangMame** [comment]
OK 我删些group

**Comment by Bryan2333** [comment]
![15184413662042095101506543993344](https://user-images.githubusercontent.com/31512600/36098459-f8aea296-1039-11e8-8b61-c3a899bcd8f4.jpg)

**Comment by YangMame** [comment]
咦 Arch又有什么变动了咩 等我过完年全删掉 /现在没电脑在旁边
自己手动systemctl enable lightdm就行了 /后面没有别的内容了

**Comment by Bryan2333** [comment]
ok
